version: "3.8"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_sf
    restart: always
    depends_on:
      - db
    ports:
    - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev



  db:
    image: mariadb:10.1
    volumes:
      - /Users/vachetghislain/Desktop/blog_P5/base_de_donnee:/var/lib/mysql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: "devpassword"
      MYSQL_DATABASE: "devdb"
    ports:
      - "3307:3306"
    networks:
      - dev
  web:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 8081:80
    volumes:
      - ./config/docker:/etc/nginx/conf.d
      - ./:/var/www
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
        - ./:/var/www
networks:
  dev:

volumes:
  db-data:


    